language: python
sudo: false
addons:
  postgresql: "9.4"
before_script:
 - "psql -c 'create database psycopg2_test;' -U postgres"
 - "psql psycopg2_test -c 'create extension hstore;' -U postgres"
env:
 - PSYCOPG2_TESTDB_USER=postgres
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "pypy"
 - "pypy3"
install: python setup.py install
script: python setup.py test
after_script:
  - "psql -c 'create database psycopg2_cffi_test_db;' -U postgres"
  - git clone https://github.com/chtd/psycopg2-benchmarks.git --depth 1
  - pip install -r psycopg2-benchmarks/django_bench/requirements.txt
  - cd psycopg2-benchmarks/django_bench/ && ./bench 1000 5
matrix:
  fast_finish: true
